### ISSUE TITLE
Can not add simple text datastore

### ISSUE THREAD

**Issue by netandreus** [gmpetrov/databerry#122]
### Issue
1. Click Datastores -> New datastore
2. Datastore type = Text, paste text, fill name input, click Finish.

### Errors

Error:
```
xhr.js:247     PUT http://minio:9000/databerry-dev/datastores/cll0tr9y2000co7if7dbjgxni/cll0tw2sc00013b79p11qj0lm/cll0tw2sc00013b79p11qj0lm.txt?Content-Type=text%2Fplain&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=root%2F20230807%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20230807T120800Z&X-Amz-Expires=900&X-Amz-Signature=6d99a7186d93ea4deb843d5eb1dd1f551d95d400b34030c9da88407e595786d7&X-Amz-SignedHeaders=host%3Bx-amz-acl&x-amz-acl=public-read 404 (Not Found)
```

AxiosError:
```
error 
AxiosError {message: 'Request failed with status code 404', name: 'AxiosError', code: 'ERR_BAD_REQUEST', config: {…}, request: XMLHttpRequest, …}
code
: 
"ERR_BAD_REQUEST"
config
: 
{transitional: {…}, adapter: Array(2), transformRequest: Array(1), transformResponse: Array(1), timeout: 0, …}
message
: 
"Request failed with status code 404"
name
: 
"AxiosError"
request
: 
XMLHttpRequest {onreadystatechange: null, readyState: 4, timeout: 0, withCredentials: false, upload: XMLHttpRequestUpload, …}
response
: 
{data: '<?xml version="1.0" encoding="UTF-8"?>\n<Error><Cod…74d3b3fd1af9251148b658df7ac2e3e8</HostId></Error>', status: 404, statusText: 'Not Found', headers: AxiosHeaders, config: {…}, …}
stack
: 
"AxiosError: Request failed with status code 404\n    at settle (webpack-internal:///./node_modules/.pnpm/axios@1.3.4/node_modules/axios/lib/core/settle.js:24:12)\n    at XMLHttpRequest.onloadend (webpack-internal:///./node_modules/.pnpm/axios@1.3.4/node_modules/axios/lib/adapters/xhr.js:117:66)"
[[Prototype]]
: 
Error
```

**Comment by JackOman69** [comment]
Did you create s3 bucket in minio?
